### ISSUE TITLE
licenses.json datetime error

### ISSUE THREAD

**Issue by y12studio** [g0v/agriculture#21]
target file : 

https://github.com/g0v/agriculture/tree/gh-pages/_raw/download/pesticide/licenses.json

日前測試農藥資料匯入 elasticsearch 分析 licenses.json，但許可有效期限日期錯誤無法正確匯入 elasticsearch，是否有人正在處理或是可提PR修正？改成 2/28 是否可行？

![agr-g0v](https://cloud.githubusercontent.com/assets/1840874/4371066/cb4a579e-4311-11e4-95e0-7f1f7d5f65be.jpg)

test code :

https://github.com/y12studio/agriculture/tree/tmp-elkpy/utils/json2elk

```
$ python convert.py
Oops! error:
{
    "國外原製造廠商": "NANTONG JIANGSHAN AGROCHEMICAL & CHEMICALS LIMITED LIABILITY CO.",
    "有效期限": "107/02/31",
    "英文名稱": "GLYPHOSATE IPA",
    "廠商名稱": "億豐農化廠股份有限公司",
    "許可證號": "00862",
    "廠牌名稱": "",
    "中文名稱": "嘉磷塞異丙胺鹽",
    "農藥代號": "H126",
    "化學成分": "isopropylamine salt of N-(phosphonomethyl)glycine"
}
```

**Comment by simonpai** [comment]
不好意思，隔了有點久才看到這個 issue。
我們原始資料來源是
http://m.coa.gov.tw/OpenData/PesticideData.aspx
我剛通知了懂農業資料的夥伴，等他問一下再來回覆你。

**Comment by y12studio** [comment]
@simonpai  看起來是原始資料有錯。

![agriculture-1](https://cloud.githubusercontent.com/assets/1840874/4689024/27afbb2a-56a2-11e4-981c-e2aeac6de0a4.jpg)

**Comment by a0kman** [comment]
這應該是公務單位原始資料的誤植問題，不太建議自行修改，或是有修改的話要標明一下原始資料的錯誤，這樣會比較好@___@"
